name: CI – Main branch

on:
  push:
    branches:
      - main

jobs:
  test-and-coverage:
    name: Run tests & collect coverage
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.10', '3.11', '3.12', '3.13']
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup QEMU for ARM
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install deps
        run: pip install -e '.[tests]'

      - name: Run tests
        run: pytest --cov --cov-report=xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-and-publish:
    name: Bump, build & publish
    needs: test-and-coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build reqs
        run: pip install -e '.[build]'

      - name: Bump version & create tag
        uses: googleapis/release-please-action@v4
        with:
          # GitHub token has write access for tags
          token: ${{ secrets.GIT_TOKEN }}
          release-type: python
          target-branch: main
          skip-github-pull-request: true

      - name: Refresh workspace to the new version
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
