name: Release on Merge

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -e '.[tests]'
          pip install -e '.[build]'

      - name: Bump version & tag directly
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          release-type: python
          target-branch: main

      - name: Refresh workspace to bumped main
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Run tests & collect coverage
        run: |
          pytest --cov --cov-report=xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
